###############################################################################
#
#   Config file for this Snakemake pipeline.
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 20-11-2019
#   LICENSE: GPL v3.0
#
###############################################################################
---

# path for the result directory
output_dir: "output_dir"

# path to the table with the RNA-Seq samples metadata
design_file: "sample_design_table.tsv"

# path to the VASTDB
VASTDB: "VASTDB"

# VAST-TOOLS parameters
species: "Hsa"
min_dPSI: "0"
min_coverage: "10"
MV_param: "0.95"

...